services:
  db:
    image: 'mysql:latest'
    restart: 'always'
    environment:
      - MYSQL_DATABASE=clinicdb
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - '3308:3306'
    volumes:
      - './mysql_opening_back_data:/var/lib/mysql'
  adminer:
    image: 'adminer:latest'
    restart: 'always'
    ports:
      - '9080:8080'
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '9020:80'
      - '9025:25'
    volumes:
      - './smtp4dev-data:/smtp4dev'
